### ISSUE TITLE
Mixer Documentation implicit section hyperlinks not working

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/clear-linux-documentation#97] opened 2018-03-15 02:35 UTC
In the recent mixer documentation rewrite (#80), the various steps were broken out into separate sections. A `Current mixing workflow` section was added to the top, with links to the various other sections below.  These hyperlinks do not currently work, and instead all point back to the [main document itself](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer).

It's not clear to me why these hyperlinks are not being generated properly. In theory, they should work, and they look correct to me. According to the reST spec, all section titles are automatically used as ["implicit hyperlink targets"](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets). The hyperlink references look correct to me -- they simply need to match the title text exactly, and they do.

We're using Sphinx to build our reST pages. The [Sphinx documentation](http://www.sphinx-doc.org/en/stable/markup/inline.html) advises against using implicit hyperlink targets like this, but only because they do not work across documents the way their `:ref:` extension does. Within a document, they are supposed to work fine.

One potential workaround would be to add ["explicit hyperlink targets"](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#explicit-hyperlink-targets) and update the hyperlink references to point to them. That could be taken a step further to use full-fledged explicit `:ref:` targets, but then they would need to be unique across the entire document set. I have not tested either approach. If both work, I would recommend the first over the latter for simplicity.

**Comment by kevincwells** [comment] 2018-03-15 02:36
@rcaballeromx  I assume you know a lot more about reST/Sphinx than I do -- any idea why they're not being built correctly?

**Comment by rcaballeromx** [comment] 2018-03-15 16:29
@kevincwells Thank you for reporting on this. We haven't used internal xrefs in the documentation so this issue hadn't become apparent. After investigating, I can say that the issue is not caused by ReST nor Sphinx. The issue is being caused by the import we perform of the rendered content into the website's CMS. The import removes the ids from the internal links leaving them pointing to the main topic. I have notified the team responsible for the import and they are working on fixing the issue. ETA for the fix is Monday.

**Comment by kevincwells** [comment] 2018-03-15 17:45
Ah, that makes sense. Awesome -- thanks for the quick investigation!

**Comment by mltullis** [comment] 2018-03-29 22:02
I believe the ODX team deployed a new stylesheet with less restrictive tag filtering hoping to fix this issue. 
It looks like more work is needed. I'll reach out to them on Monday (after their holiday) to ensure we get this fixed.

**Comment by rcaballeromx** [comment] 2018-04-06 16:01
@kevincwells I can confirm that the issue is back. It is strange because we already deployed a fix. ODX and I will investigate further.

**Comment by iphutch** [comment] 2018-04-17 16:43
Issue is not limited to Mixer docs: There are multiple scenarios in which the sidebar or content pages once you move to a tab does not link the user to the content indicated. Here are a few examples with the tab stated first, then the top level heading, then the heading/link with the issue.
Concepts: Bundles -> Next steps
Reference: Compatible Clear Linux Kernel -> Kernel Native
Tutorial: Machine learning tutorial -> Install and configure a Clear Linux Host OS on bare metal

**Comment by mltullis** [comment] 2018-04-17 19:44
Yes, this style sheet issue for bookmarked internal links affects all topics, not just mixer. @rcaballeromx, do you have any update from Daniel Serna on the ODX team?

**Comment by tpleavitt** [comment] 2018-05-23 17:09
@rcaballeromx , can we close this issue?

**Comment by rcaballeromx** [comment] 2018-05-23 17:28
@tpleavitt: My last status is that ODX was still working on a fix.

**Comment by kevincwells** [comment] 2018-05-23 17:40
@tpleavitt @rcaballeromx  -- checking right now, the links on the mixer page (that I originally opened this issue about) appear to work.  Don't know about any other issues, like those @iphutch  or @mltullis  mentioned.

**Comment by rcaballeromx** [comment] 2018-05-23 17:53
@kevincwells Yes, the original issue is fixed and I just spoke with ODX. Today's deployment should fix the other issues too. Daniel Serna will do the deployment today by EoD.

**Comment by tpleavitt** [comment] 2018-06-05 21:12
I verified that the issues reported by @iphutch are also fixed.  Closing this issue

**Closed by tpleavitt** 2018-06-05 21:12 UTC
